"""SQLite persistence adapters for real trades and structured fee plans.

Execution timestamps are naive Asia/Shanghai wall-clock values at second
precision, matching the shared trade contract.  ``created_at`` and
``updated_at`` are UTC ISO-8601 audit timestamps generated by the App database
boundary; they must not be interpreted as exchange-local execution times.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from enum import StrEnum
import math
import sqlite3
from typing import Any, Callable, TypeVar

from packages.t0assistant.preferences import PreferenceCapability
from packages.t0assistant.trading import (
    TradeDraft,
    TradeRecord,
    TradeScope,
    TradeSide,
)

from .app_database import AppDatabase, AppDatabaseWriteBoundary, _utc_now


_TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"
_T = TypeVar("_T")


class RepositoryPersistenceError(RuntimeError):
    """A stable failure raised when App-private persistence is not confirmed."""


class RepositoryReadOnlyError(RepositoryPersistenceError):
    """The App database remains readable but mutations are disabled."""


class RepositoryNotFoundError(RepositoryPersistenceError):
    """The requested persistent record does not exist."""


class RepositoryConflictError(RepositoryPersistenceError):
    """A create operation conflicts with an existing persistent identity."""

    def __init__(self, entity: str, conflict_id: str, message: str) -> None:
        self.entity = entity
        self.conflict_id = conflict_id
        super().__init__(message)


class TransferFeeSide(StrEnum):
    BUY = "buy"
    SELL = "sell"
    BOTH = "both"


def _required_text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field}: must not be blank")
    return value.strip()


def _non_negative_decimal(value: Any, field: str) -> Decimal:
    if isinstance(value, bool) or value is None:
        raise ValueError(f"{field}: must be a finite non-negative number")
    if isinstance(value, float) and not math.isfinite(value):
        raise ValueError(f"{field}: must be a finite non-negative number")
    try:
        result = Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise ValueError(
            f"{field}: must be a finite non-negative number"
        ) from exc
    if not result.is_finite() or result < 0:
        raise ValueError(f"{field}: must be a finite non-negative number")
    return result


@dataclass(frozen=True, slots=True)
class FeePlanRecord:
    """Structured fee-plan values; fee calculation belongs to a later policy."""

    fee_plan_id: str
    name: str
    a_share_commission_rate: Decimal
    a_share_min_commission: Decimal
    etf_commission_rate: Decimal
    etf_min_commission: Decimal
    stamp_duty_rate: Decimal
    stamp_duty_sell_only: bool
    transfer_fee_rate: Decimal
    transfer_fee_side: TransferFeeSide
    transfer_fee_enabled: bool

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "fee_plan_id", _required_text(self.fee_plan_id, "fee_plan_id")
        )
        object.__setattr__(self, "name", _required_text(self.name, "name"))
        for field_name in (
            "a_share_commission_rate",
            "a_share_min_commission",
            "etf_commission_rate",
            "etf_min_commission",
            "stamp_duty_rate",
            "transfer_fee_rate",
        ):
            object.__setattr__(
                self,
                field_name,
                _non_negative_decimal(getattr(self, field_name), field_name),
            )
        if not isinstance(self.stamp_duty_sell_only, bool):
            raise ValueError("stamp_duty_sell_only: must be a boolean")
        if not isinstance(self.transfer_fee_enabled, bool):
            raise ValueError("transfer_fee_enabled: must be a boolean")
        try:
            side = TransferFeeSide(self.transfer_fee_side)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                "transfer_fee_side: must be one of: buy, sell, both"
            ) from exc
        object.__setattr__(self, "transfer_fee_side", side)


class _SqliteRepository:
    def __init__(self, database: AppDatabase) -> None:
        self._database = database
        self._boundary = AppDatabaseWriteBoundary(
            database.connection,
            writable=database.capability.writable,
            lock=database._lock,
        )

    @property
    def capability(self) -> PreferenceCapability:
        return self._database.capability

    def _read(self, operation: Callable[[sqlite3.Connection], _T]) -> _T:
        return self._boundary.read(
            operation,
            error_type=RepositoryPersistenceError,
            message="本地成交与设置读取失败",
        )

    def _run(self, operation: Callable[[sqlite3.Connection], _T]) -> _T:
        reason = self.capability.reason or (
            "本地成交与设置文件为只读；成交和收费方案不能修改或保存"
        )
        return self._boundary.run(
            operation,
            read_only_error_type=RepositoryReadOnlyError,
            persistence_error_type=RepositoryPersistenceError,
            read_only_message=reason,
            failure_message="本地成交与设置保存失败，未确认持久化",
        )

    @staticmethod
    def _insert(
        connection: sqlite3.Connection,
        statement: str,
        parameters: tuple[Any, ...],
        *,
        entity: str,
        conflict_id: str,
        display_name: str,
    ) -> None:
        try:
            connection.execute(statement, parameters)
        except sqlite3.IntegrityError as exc:
            if getattr(exc, "sqlite_errorname", None) in {
                "SQLITE_CONSTRAINT_PRIMARYKEY",
                "SQLITE_CONSTRAINT_UNIQUE",
            }:
                raise RepositoryConflictError(
                    entity,
                    conflict_id,
                    f"{display_name}已存在：{conflict_id}",
                ) from exc
            raise


class SqliteTradeRepository(_SqliteRepository):
    """CRUD adapter for persisted real trades only."""

    def create(self, record: TradeRecord) -> TradeRecord:
        self._require_real(record)
        now = _utc_now()

        def persist(connection: sqlite3.Connection) -> TradeRecord:
            self._insert(
                connection,
                """
                INSERT INTO trades(
                    trade_id, symbol, trade_date, side, executed_at, price,
                    quantity, fee, note, fee_plan_id, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                self._record_values(record) + (now, now),
                entity="trade",
                conflict_id=record.trade_id,
                display_name="成交记录",
            )
            return record

        return self._run(persist)

    def get(self, trade_id: str) -> TradeRecord | None:
        normalized_id = _required_text(trade_id, "trade_id")
        return self._read(
            lambda connection: self._from_row(
                connection.execute(
                    "SELECT * FROM trades WHERE trade_id = ?", (normalized_id,)
                ).fetchone()
            )
        )

    def list_all(self) -> tuple[TradeRecord, ...]:
        return self._read(
            lambda connection: tuple(
                self._from_row(row)
                for row in connection.execute(
                    """
                    SELECT * FROM trades
                    ORDER BY executed_at, trade_id
                    """
                ).fetchall()
            )
        )

    def list_for_symbol_and_date(
        self, symbol: str, trade_date: date | str
    ) -> tuple[TradeRecord, ...]:
        normalized_date = self._normalize_date(trade_date)
        return self._read(
            lambda connection: tuple(
                self._from_row(row)
                for row in connection.execute(
                    """
                    SELECT * FROM trades
                    WHERE symbol = ? AND trade_date = ?
                    ORDER BY executed_at, trade_id
                    """,
                    (symbol, normalized_date),
                ).fetchall()
            )
        )

    def update(self, record: TradeRecord) -> TradeRecord:
        self._require_real(record)
        now = _utc_now()

        def persist(connection: sqlite3.Connection) -> TradeRecord:
            cursor = connection.execute(
                """
                UPDATE trades
                SET symbol = ?, trade_date = ?, side = ?, executed_at = ?,
                    price = ?, quantity = ?, fee = ?, note = ?,
                    fee_plan_id = ?, updated_at = ?
                WHERE trade_id = ?
                """,
                self._record_values(record)[1:] + (now, record.trade_id),
            )
            if cursor.rowcount != 1:
                raise RepositoryNotFoundError(
                    f"成交记录不存在：{record.trade_id}"
                )
            return record

        return self._run(persist)

    def delete(self, trade_id: str) -> bool:
        normalized_id = _required_text(trade_id, "trade_id")
        return self._run(
            lambda connection: connection.execute(
                "DELETE FROM trades WHERE trade_id = ?", (normalized_id,)
            ).rowcount
            == 1
        )

    @staticmethod
    def _require_real(record: TradeRecord) -> None:
        if not isinstance(record, TradeRecord):
            raise TypeError("record must be a TradeRecord")
        if record.trade.trade_scope is not TradeScope.REAL:
            raise ValueError("only real trades may be persisted")

    @staticmethod
    def _record_values(record: TradeRecord) -> tuple[Any, ...]:
        trade = record.trade
        return (
            record.trade_id,
            trade.symbol,
            trade.executed_at.date().isoformat(),
            trade.side.value,
            trade.executed_at.strftime(_TIMESTAMP_FORMAT),
            str(trade.price),
            trade.quantity,
            None if trade.fee is None else str(trade.fee),
            trade.note,
            trade.fee_plan_id,
        )

    @staticmethod
    def _from_row(row: sqlite3.Row | None) -> TradeRecord | None:
        if row is None:
            return None
        return TradeRecord(
            trade_id=row["trade_id"],
            trade=TradeDraft(
                trade_scope=TradeScope.REAL,
                symbol=row["symbol"],
                side=TradeSide(row["side"]),
                executed_at=datetime.strptime(row["executed_at"], _TIMESTAMP_FORMAT),
                price=Decimal(row["price"]),
                quantity=row["quantity"],
                fee=None if row["fee"] is None else Decimal(row["fee"]),
                note=row["note"],
                fee_plan_id=row["fee_plan_id"],
            ),
        )

    @staticmethod
    def _normalize_date(value: date | str) -> str:
        if isinstance(value, datetime):
            raise ValueError("trade_date must be a date without time")
        if isinstance(value, date):
            return value.isoformat()
        if isinstance(value, str):
            try:
                return date.fromisoformat(value).isoformat()
            except ValueError as exc:
                raise ValueError("trade_date must use YYYY-MM-DD") from exc
        raise ValueError("trade_date must use YYYY-MM-DD")


class SqliteFeePlanRepository(_SqliteRepository):
    """CRUD adapter for structured fee plans without fee-policy behavior."""

    def initialize_default_plan(
        self, plan: FeePlanRecord
    ) -> FeePlanRecord | None:
        """Atomically seed the default plan exactly once per database.

        The initialization flag and the plan row are written in the same
        transaction. If the flag is already set, this method returns the
        persisted plan or ``None`` if the user deleted it later, so the
        default plan never resurrects on restart.
        """

        self._require_plan(plan)

        def persist(connection: sqlite3.Connection) -> FeePlanRecord | None:
            row = connection.execute(
                "SELECT default_plan_initialized FROM fee_plan_meta WHERE singleton_id = 1"
            ).fetchone()
            if row is not None and bool(row["default_plan_initialized"]):
                return self._from_row(
                    connection.execute(
                        "SELECT * FROM fee_plans WHERE fee_plan_id = ?",
                        (plan.fee_plan_id,),
                    ).fetchone()
                )

            now = _utc_now()
            self._insert(
                connection,
                """
                INSERT INTO fee_plans(
                    fee_plan_id, name, a_share_commission_rate,
                    a_share_min_commission, etf_commission_rate,
                    etf_min_commission, stamp_duty_rate,
                    stamp_duty_sell_only, transfer_fee_rate,
                    transfer_fee_side, transfer_fee_enabled,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                self._plan_values(plan) + (now, now),
                entity="fee_plan",
                conflict_id=plan.fee_plan_id,
                display_name="收费方案",
            )
            connection.execute(
                """
                INSERT INTO fee_plan_meta (singleton_id, default_plan_initialized, updated_at)
                VALUES (1, 1, ?)
                ON CONFLICT(singleton_id) DO UPDATE SET
                    default_plan_initialized = excluded.default_plan_initialized,
                    updated_at = excluded.updated_at
                """,
                (now,),
            )
            return plan

        return self._run(persist)

    def create(self, plan: FeePlanRecord) -> FeePlanRecord:
        self._require_plan(plan)
        now = _utc_now()

        def persist(connection: sqlite3.Connection) -> FeePlanRecord:
            self._insert(
                connection,
                """
                INSERT INTO fee_plans(
                    fee_plan_id, name, a_share_commission_rate,
                    a_share_min_commission, etf_commission_rate,
                    etf_min_commission, stamp_duty_rate,
                    stamp_duty_sell_only, transfer_fee_rate,
                    transfer_fee_side, transfer_fee_enabled,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                self._plan_values(plan) + (now, now),
                entity="fee_plan",
                conflict_id=plan.fee_plan_id,
                display_name="收费方案",
            )
            return plan

        return self._run(persist)

    def get(self, fee_plan_id: str) -> FeePlanRecord | None:
        normalized_id = _required_text(fee_plan_id, "fee_plan_id")
        return self._read(
            lambda connection: self._from_row(
                connection.execute(
                    "SELECT * FROM fee_plans WHERE fee_plan_id = ?",
                    (normalized_id,),
                ).fetchone()
            )
        )

    def list_all(self) -> tuple[FeePlanRecord, ...]:
        return self._read(
            lambda connection: tuple(
                self._from_row(row)
                for row in connection.execute(
                    "SELECT * FROM fee_plans ORDER BY name, fee_plan_id"
                ).fetchall()
            )
        )

    def update(self, plan: FeePlanRecord) -> FeePlanRecord:
        self._require_plan(plan)
        now = _utc_now()

        def persist(connection: sqlite3.Connection) -> FeePlanRecord:
            cursor = connection.execute(
                """
                UPDATE fee_plans
                SET name = ?, a_share_commission_rate = ?,
                    a_share_min_commission = ?, etf_commission_rate = ?,
                    etf_min_commission = ?, stamp_duty_rate = ?,
                    stamp_duty_sell_only = ?, transfer_fee_rate = ?,
                    transfer_fee_side = ?, transfer_fee_enabled = ?,
                    updated_at = ?
                WHERE fee_plan_id = ?
                """,
                self._plan_values(plan)[1:] + (now, plan.fee_plan_id),
            )
            if cursor.rowcount != 1:
                raise RepositoryNotFoundError(
                    f"收费方案不存在：{plan.fee_plan_id}"
                )
            return plan

        return self._run(persist)

    def delete(self, fee_plan_id: str) -> bool:
        normalized_id = _required_text(fee_plan_id, "fee_plan_id")
        return self._run(
            lambda connection: connection.execute(
                "DELETE FROM fee_plans WHERE fee_plan_id = ?",
                (normalized_id,),
            ).rowcount
            == 1
        )

    @staticmethod
    def _require_plan(plan: FeePlanRecord) -> None:
        if not isinstance(plan, FeePlanRecord):
            raise TypeError("plan must be a FeePlanRecord")

    @staticmethod
    def _plan_values(plan: FeePlanRecord) -> tuple[Any, ...]:
        return (
            plan.fee_plan_id,
            plan.name,
            str(plan.a_share_commission_rate),
            str(plan.a_share_min_commission),
            str(plan.etf_commission_rate),
            str(plan.etf_min_commission),
            str(plan.stamp_duty_rate),
            int(plan.stamp_duty_sell_only),
            str(plan.transfer_fee_rate),
            plan.transfer_fee_side.value,
            int(plan.transfer_fee_enabled),
        )

    @staticmethod
    def _from_row(row: sqlite3.Row | None) -> FeePlanRecord | None:
        if row is None:
            return None
        return FeePlanRecord(
            fee_plan_id=row["fee_plan_id"],
            name=row["name"],
            a_share_commission_rate=Decimal(row["a_share_commission_rate"]),
            a_share_min_commission=Decimal(row["a_share_min_commission"]),
            etf_commission_rate=Decimal(row["etf_commission_rate"]),
            etf_min_commission=Decimal(row["etf_min_commission"]),
            stamp_duty_rate=Decimal(row["stamp_duty_rate"]),
            stamp_duty_sell_only=bool(row["stamp_duty_sell_only"]),
            transfer_fee_rate=Decimal(row["transfer_fee_rate"]),
            transfer_fee_side=TransferFeeSide(row["transfer_fee_side"]),
            transfer_fee_enabled=bool(row["transfer_fee_enabled"]),
        )
