"""Shared runtime contract between T0-020 and T0-045.

This module freezes the small, transport-independent boundary shared by the
bounded computation executor (:mod:`packages.t0assistant.runtime.computation_executor`)
and the Replay data preparation module (:mod:`packages.t0assistant.runtime.replay_data`).

The contract deliberately avoids leaking Electron, HTTP, React or Replay JSON
Schema types into the executor.  Only the minimum semantic surface needed to
coordinate priority, cancellation, timeout, supersession and result acceptance
is exposed here.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Callable, Mapping, Protocol, Sequence
from uuid import uuid4


class ComputationPriority(enum.IntEnum):
    """Fixed shared-resource priority ordering.

    Lower integer means higher scheduling priority.  The ordering is fixed by
    the T+0 architecture: Live real-time work always wins over user-interactive
    Replay work, which always wins over Replay background prefetch/prepare.
    """

    LIVE = 0
    REPLAY_INTERACTIVE = 1
    REPLAY_PREFETCH = 2


class CancelReason(enum.Enum):
    """Why a computation task was cancelled or its result rejected.

    The values map onto the stable Replay v1.0 error vocabulary; they are not
    themselves the public error codes.  The executor returns a
    :class:`ComputationOutcome` that the caller translates into the stable
    error code at the result-acceptance boundary.
    """

    #: The caller explicitly cancelled the task before it produced a result.
    CANCELLED = "cancelled"

    #: A newer seek/step superseded this operation for the same Session.
    SUPERSEDED = "superseded"

    #: The absolute deadline elapsed before the task produced a usable result.
    DEADLINE_EXCEEDED = "deadline_exceeded"

    #: The owning Session retired or its generation changed while the task ran.
    SESSION_INVALID = "session_invalid"

    #: The executor has shut down and can no longer accept or run the task.
    EXECUTOR_CLOSED = "executor_closed"


@dataclass(frozen=True, slots=True)
class PipelineInstanceIdentity:
    """Stable identity for a :class:`WorkbenchPipeline` instance.

    The executor uses object identity (``id(pipeline)``) plus this opaque token
    to guarantee that two tasks targeting the same pipeline instance never run
    concurrently, and that a late result cannot mutate a different pipeline
    instance that happens to reuse the same memory address.
    """

    instance_id: int
    generation: int
    session_id: str


@dataclass(frozen=True, slots=True)
class ComputationTask:
    """Immutable description of one bounded computation task.

    Attributes:
        task_id: opaque unique identifier generated by the caller or executor.
        session_id: owning Session identifier; required so late results can be
            isolated when the Session retires.
        session_generation: the Session generation captured at submission time.
            A mismatch at acceptance time means the result must be discarded.
        pipeline_identity: identity of the pipeline instance whose mutable
            state the callable will advance.  The executor serialises all
            tasks that share the same identity.
        priority: scheduling priority.  Must be one of the
            :class:`ComputationPriority` values.
        callable: the computation to run.  It receives the task itself as its
            sole argument so it can perform cooperative cancellation checks
            against ``is_cancelled``.
        operation_id: optional Replay operation identifier.  When non-empty,
            a newer seek on the same Session supersedes every outstanding task
            carrying an earlier operation id.
        deadline: absolute monotonic deadline, expressed as
            ``time.monotonic()`` seconds.  The executor enforces it both while
            the task is queued and while it runs.
        is_cancelled: cooperative cancellation predicate invoked before
            execution and at acceptance time.  Returning ``True`` means the
            task should be skipped or its result rejected.
        is_session_valid: Session lifecycle predicate invoked at acceptance
            time.  Returning ``False`` isolates the late result without
            raising.
        accept_result: final acceptance predicate invoked after the callable
            succeeds.  It receives the produced value and must return ``True``
            only when the result still belongs to the active Session,
            generation, pipeline instance and operation.
        commit_result: optional state-commit callback invoked only after the
            executor has re-validated cancellation, deadline, Session
            validity, supersession and ``accept_result``.  This lets callers
            compute an isolated preview first and mutate shared state only at
            the final acceptance boundary.
    """

    task_id: str
    session_id: str
    session_generation: int
    pipeline_identity: PipelineInstanceIdentity
    priority: ComputationPriority
    callable: Callable[["ComputationTask"], Any]
    operation_id: str | None = None
    deadline: float | None = None
    is_cancelled: Callable[[], bool] | None = None
    is_session_valid: Callable[[], bool] | None = None
    accept_result: Callable[[Any], bool] | None = None
    commit_result: Callable[[Any], None] | None = None

    def with_task_id(self, task_id: str) -> "ComputationTask":
        """Return a copy with a different ``task_id`` (used by the executor)."""

        return ComputationTask(
            task_id=task_id,
            session_id=self.session_id,
            session_generation=self.session_generation,
            pipeline_identity=self.pipeline_identity,
            priority=self.priority,
            callable=self.callable,
            operation_id=self.operation_id,
            deadline=self.deadline,
            is_cancelled=self.is_cancelled,
            is_session_valid=self.is_session_valid,
            accept_result=self.accept_result,
            commit_result=self.commit_result,
        )


@dataclass(frozen=True, slots=True)
class ComputationOutcome:
    """Structured result returned by the executor for one submitted task.

    The executor never publishes events.  A caller inspects ``status`` and,
    for ``status == COMPLETED``, retrieves ``value``.  For any non-completed
    status the caller maps ``cancel_reason`` onto the stable Replay error
    vocabulary at the acceptance boundary.

    Attributes:
        task_id: the task id this outcome refers to.
        status: one of :class:`ComputationStatus`.
        value: the callable's return value when ``status == COMPLETED``;
            ``None`` otherwise.
        cancel_reason: structured reason when ``status`` is not ``COMPLETED``.
        exception: the original exception when ``status == FAILED``.  It is
            kept here so the caller can preserve the chain while exposing only
            the stable ``calculation_failed`` error code across the Replay API.
    """

    task_id: str
    status: "ComputationStatus"
    value: Any = None
    cancel_reason: CancelReason | None = None
    exception: BaseException | None = None


class ComputationStatus(enum.Enum):
    """Terminal status of a submitted computation task."""

    #: The callable returned a value that passed the acceptance predicate.
    COMPLETED = "completed"

    #: The callable raised an exception.  See ``ComputationOutcome.exception``.
    FAILED = "failed"

    #: The task was cancelled, superseded, timed out or isolated.
    CANCELLED = "cancelled"


class ComputationExecutorPort(Protocol):
    """Executor boundary consumed by Replay/Live Session code."""

    def submit(self, task: ComputationTask) -> "ComputationFuture": ...

    def shutdown(
        self,
        *,
        cancel_pending: bool = False,
        wait: bool = True,
    ) -> None: ...


class ComputationFuture(Protocol):
    """Future-like handle returned by the executor.

    The future is deliberately minimal: ``result()`` blocks until the outcome
    is ready and returns the :class:`ComputationOutcome`.  A ``timeout``
    argument only bounds the *wait*; it does not cancel the underlying task.
    Cancellation is performed through the executor-supplied task predicate or
    through ``cancel_pending`` at shutdown.
    """

    def result(self, *, timeout: float | None = None) -> ComputationOutcome: ...

    def done(self) -> bool: ...


@dataclass(frozen=True, slots=True)
class ReplayReliabilityAssessment:
    """Outcome of assessing local + remote bars for one Replay granularity.

    ``is_reliable`` is the authoritative signal: ``True`` means the prepared
    sequence can drive a Replay cursor without fabricating bars or crossing
    gaps.  ``covered_missing_ranges`` records the date ranges that had to be
    fetched from the provider; ``uncovered_missing_ranges`` records the ranges
    that remain missing after best-effort backfill.
    """

    granularity: str
    is_reliable: bool
    bar_count: int
    covered_missing_ranges: tuple[tuple[str, str], ...] = ()
    uncovered_missing_ranges: tuple[tuple[str, str], ...] = ()


@dataclass(frozen=True, slots=True)
class PreparedReplayData:
    """Immutable, network-free Replay input prepared before ``ready``.

    All sequences are sorted ascending by timestamp, deduplicated, and use
    closed-bar timestamps.  ``actual_bar_times`` contains only timestamps that
    belong to the selected granularity, so T0-046 can advance the simulated
    clock from one actual bar close to the next without fabricating lunch or
    suspension slots.

    The ``market_input_port`` is a pure-memory reader: calling ``read`` never
    touches the provider or SQLite, and never returns data past ``target_time``.
    """

    symbol: str
    market_session: Any
    trade_date: str
    granularity: str
    preheat_5m_bars: tuple[Mapping[str, Any], ...]
    bars_1m: tuple[Mapping[str, Any], ...]
    official_5m_bars: tuple[Mapping[str, Any], ...]
    daily_bars_history: tuple[Mapping[str, Any], ...]
    quote_snapshots: tuple[Mapping[str, Any], ...]
    actual_bar_times: tuple[datetime, ...]
    start_time: datetime
    end_time: datetime
    previous_close: float | int | None
    warnings: tuple[Mapping[str, Any], ...]
    market_input_port: "ReplayMarketInputPort"
    assessment_1m: ReplayReliabilityAssessment | None
    assessment_5m: ReplayReliabilityAssessment | None
    preheat_30m_bars: tuple[Mapping[str, Any], ...] = ()
    official_30m_bars: tuple[Mapping[str, Any], ...] = ()


class ReplayMarketInputPort(Protocol):
    """Pure-memory market input port backed by :class:`PreparedReplayData`.

    ``read(target_time)`` returns a :class:`PipelineMarketInput` whose
    sequences are the prefix of the prepared data at or before ``target_time``.
    It never performs I/O and never exposes future bars, quotes, indicators or
    CZSC output.  Repeated calls with the same ``target_time`` return equal
    prefixes.
    """

    def read(self, target_time: datetime) -> Any: ...


def new_task_id() -> str:
    """Generate an opaque, unique task identifier."""

    return uuid4().hex


def default_accept_result(_value: Any) -> bool:
    """Default acceptance predicate that accepts any non-exceptional result."""

    return True


__all__ = [
    "CancelReason",
    "ComputationExecutorPort",
    "ComputationFuture",
    "ComputationOutcome",
    "ComputationPriority",
    "ComputationStatus",
    "ComputationTask",
    "PipelineInstanceIdentity",
    "PreparedReplayData",
    "ReplayMarketInputPort",
    "ReplayReliabilityAssessment",
    "default_accept_result",
    "new_task_id",
]
